export const languages = [
    "Auto-detect",
    "Afrikaans",
    "Albanian",
    "Amharic",
    "Arabic",
    "Armenian (Eastern)",
    "Armenian (Western)",
    "Azerbaijani (Azeri)",
    "Bassa",
    "Belarusian",
    "Bengali",
    "Bosnian",
    "Braille",
    "Bulgarian",
    "Burmese",
    "Cambodian (Khmer)",
    "Cape Verde Creole",
    "Cebuano",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Chuukese",
    "Croatian",
    "Czech",
    "Danish",
    "Dari",
    "Dutch",
    "English",
    "Estonian",
    "Farsi (Persian)",
    "Finnish",
    "Flemmish",
    "French (Canada)",
    "French (France)",
    "Fulani",
    "Georgian",
    "German",
    "Greek",
    "Gujarati",
    "Haitian Creole",
    "Hakha Chin",
    "Hakka (Chinese)",
    "Hebrew",
    "Hindi",
    "Hmong",
    "Hungarian",
    "Icelandic",
    "Igbo/Ibo",
    "Ilocano",
    "Ilonggo (Hiligaynon)",
    "Indonesian",
    "Italian",
    "Japanese",
    "Javanese",
    "Kannada",
    "Karen",
    "Kazakh",
    "Kinyarwanda",
    "Kirundi",
    "Korean",
    "Kurdish (Kurmanji dialect)",
    "Kurdish (Sorani dialect)",
    "Kyrgyz/Kirgiz",
    "Lao (Laotian)",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Malay (Malaysian)",
    "Mandinka",
    "Marathi",
    "Marshallese",
    "Mien",
    "Mongolian",
    "Montenegrin",
    "Navajo",
    "Nepali",
    "Norwegian",
    "Oromo",
    "Pashto",
    "Polish",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Punjabi",
    "Rohingya",
    "Romanian (Moldavan)",
    "Russian",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Somali",
    "Spanish (Castilian)",
    "Spanish (Latin American)",
    "Spanish (other varieties)",
    "Swahili",
    "Swedish",
    "Tagalog",
    "Tamil",
    "Telugu",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Vietnamese",
    "Wolof",
    "Yoruba"
];